name: Shellcheck JSC QEMU System

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Shellcheck
        run: apt-get update && apt-get install -y shellcheck
      - name: Check
        run: shellcheck -x *.sh

